# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  deploy_infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: "aws cloudformation create-stack --stack-name circle-deploy --template-body file://template.yml"
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "bb:ff:0c:44:aa:81:4a:a8:a5:e6:4c:a2:f7:22:79:23"
            - "3b:96:f1:94:bb:20:ff:91:1f:3b:3d:cd:71:88:b1:8d"
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: Configure server
          command: |
            ansible-playbook -i ansible/inventory ansible/main.yml

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - configure_infrastructure